### ISSUE TITLE
cmd dot not found

### ISSUE THREAD

**Issue by zdhuangelephant** [phodal/coca#11]
os: window10
coca's branch: master

exceptions from console output:
cmd.Run() failed with: exec: "dot": executable file not found in %PATH%, what's the matter, please help me

**Comment by phodal** [comment]
follow README install [Graphviz](https://www.graphviz.org)

<img width="525" alt="image" src="https://user-images.githubusercontent.com/472311/84566624-57a71c00-ada5-11ea-8441-106950257c10.png">

**Comment by zdhuangelephant** [comment]
多谢， 刚刚也google下，是需要下载图片生成工具的，很是感谢您
