### ISSUE TITLE
命令行安装失败

### ISSUE THREAD

**Issue by eanfs** [phodal/coca#12]
MacBookPro coca % go get -u github.com/phodal/coca
go: golang.org/x/text upgrade => v0.3.3
go: github.com/mattn/go-runewidth upgrade => v0.0.9
go: github.com/spf13/pflag upgrade => v1.0.5
go: gonum.org/v1/gonum upgrade => v0.7.0
go: gopkg.in/yaml.v2 upgrade => v2.3.0
MacBookPro coca % coca         
zsh: command not found: coca

**Comment by phodal** [comment]
确认一下你的 Go 版本是不是和要求一样。
