### ISSUE TITLE
建议README.md里面加上windows,linux,mac安装包地址，点击可以直接下载

### ISSUE THREAD

**Issue by xiaozhiliaoo** [phodal/coca#20]
**Describe the solution you'd like**

README.md 里面建议加上https://github.com/phodal/coca/releases 发布页的windows,linux,mac安装包地址，点击可以直接下载，看到README.md里面是根据go get获取的，对非go程序员不友好，找了一会才找到安装包。主要没有一开始想到在releases 里面找....

**Comment by phodal** [comment]
欢迎来个 PR

**Comment by xiaozhiliaoo** [comment]
+1

**Comment by xiaozhiliaoo** [comment]
fix at this pr:  https://github.com/phodal/coca/pull/21
