### ISSUE TITLE
golang support

### ISSUE THREAD

**Issue by eastfisher** [phodal/coca#3]
Will coca support go language in the future?

**Comment by phodal** [comment]
Everything is possible in the future. 

But, If I will support Golang, I will use other language for fun.

**Comment by eastfisher** [comment]
OK, thanks!

**Comment by phodal** [comment]
basic support with https://github.com/phodal/coca/commit/f5f1b2ea4d9e313c6020ef29b3a595421cb48150

welcome to PR
