### ISSUE TITLE
coca v2.4.1版本 coca_windows.exe，双击或者cmd启动都会闪退

### ISSUE THREAD

**Issue by gooqhy** [phodal/coca#38]
**Describe the bug**
如图会出现以下提示后一闪而过，不清楚是我操作步骤问题 还是其他原因呢？
目前只有Windows版本电脑 没试过其他环境
![image](https://github.com/phodal/coca/assets/13540768/e4436d7f-b2a5-4588-a0da-b4d3288e6a64)

其他操作方式
1、start C:\Users\crqsh\Desktop\coca_windows.exe 
2、![image](https://github.com/phodal/coca/assets/13540768/42eef41f-3197-4407-bd8f-23aa701007e3)
3、![image](https://github.com/phodal/coca/assets/13540768/21048026-b651-4ada-b898-4936ac322b89)
都不行

**Comment by phodal** [comment]
看上去 3 是 OK 的

**Comment by gooqhy** [comment]
小白不太清楚输出物是什么形式呈现的，是安装了graphviz的，需要制定代码的路径还是需要在对应代码目录下执行呢？

**Comment by phodal** [comment]
analysis 完应该有一个数据的目录，然后就可以执行其它命令了

**Comment by gooqhy** [comment]
命令可以执行 不过生成出来的图片和项目好像没啥关系
![image](https://github.com/phodal/coca/assets/13540768/863c61d7-3fd6-47fb-8361-f1141a5ef764)

**Comment by phodal** [comment]
路径之类的配置错了吧，而且这个是系统运行的耗时分析

**Comment by gooqhy** [comment]
我直接在代码工程目录下cmd执行得到，没有改配置路径之类的，需要在配置文件修改路径吗？

**Comment by gooqhy** [comment]
重新试了一个项目又可以啦 谢谢
