### ISSUE TITLE
coca rcall -c层级太深有可能分析不出结果吗？测试某个方法输出空，往上找个层级再分析就有数据了

### ISSUE THREAD

**Issue by lanhaoit** [phodal/coca#7]

**Comment by phodal** [comment]
那可能是 bug，如果有代码就好了。

**Comment by lanhaoit** [comment]
我写了个测试，代码很简单，超过6层就不行了。
![image](https://user-images.githubusercontent.com/5336713/72069726-c679d800-3322-11ea-888b-b56e4b614d66.png)

**Comment by lanhaoit** [comment]
跟这块代码有关吗？
func BuildCallChain(funcName string, methodMap map[string][]string, diMap map[string]string) string {
	if loopCount > 6 {
		return "\n"
	}
	loopCount++

**Comment by phodal** [comment]
有关，你这继承太深了，会出现各种 bug 吧……  真实项目就是这样的？

**Comment by lanhaoit** [comment]
正在重构之前的老代码，需要做梳理，刚好就用这个工具分析了下。
嗯，业务代码存在嵌套比较深的代码。

**Comment by lanhaoit** [comment]
老代码经过各种迭代，是有可能存在这种情况的。。。
更突显重构的必要性了，哈哈！

**Comment by phodal** [comment]
哈哈，那你可以读读这个： https://github.com/phodal/migration

这个 6 是个问题，我晚点看看怎么修，当时是因为构造函数造成的 bug...，先临时写了个 6

**Comment by lanhaoit** [comment]
:ok_hand: 多谢解答

**Comment by phodal** [comment]
@lanhaoit 来分享一下你的测试代码吗？或者是否考虑修一下这个 bug，哈哈
